"""added trades table

Revision ID: 1fe0a89ffe50
Revises: c68e7bbc89ae
Create Date: 2026-02-01 16:38:05.195950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe0a89ffe50'
down_revision: Union[str, None] = 'c68e7bbc89ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signal_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_outcome'), 'trades', ['outcome'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_outcome'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
