"""

Revision ID: 34f1659ac5f0
Revises: 6feb8af8ee03
Create Date: 2026-02-05 10:23:22.862575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f1659ac5f0'
down_revision: Union[str, None] = '6feb8af8ee03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picker_suggestions', sa.Column('suggested_price', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picker_suggestions', 'suggested_price')
    # ### end Alembic commands ###
