"""added discovery tables

Revision ID: 397ca6a8afc7
Revises: 7da48d279115
Create Date: 2026-02-04 18:15:02.778071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '397ca6a8afc7'
down_revision: Union[str, None] = '7da48d279115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('picker_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('picker_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovered_symbols_discovered_at', 'discovered_symbols', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_discovered_symbols_picker_name'), 'discovered_symbols', ['picker_name'], unique=False)
    op.create_index(op.f('ix_discovered_symbols_symbol'), 'discovered_symbols', ['symbol'], unique=False)
    op.create_index('ix_discovered_symbols_symbol_picker', 'discovered_symbols', ['symbol', 'picker_name'], unique=False)
    op.create_table('picker_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('picker_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forward_return_1d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('forward_return_5d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('forward_return_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picker_suggestions_picker_name'), 'picker_suggestions', ['picker_name'], unique=False)
    op.create_index(op.f('ix_picker_suggestions_suggested_at'), 'picker_suggestions', ['suggested_at'], unique=False)
    op.create_index(op.f('ix_picker_suggestions_symbol'), 'picker_suggestions', ['symbol'], unique=False)
    op.create_index('ix_picker_suggestions_symbol_picker', 'picker_suggestions', ['symbol', 'picker_name'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_active'), 'watchlist', ['active'], unique=False)
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_active'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('ix_picker_suggestions_symbol_picker', table_name='picker_suggestions')
    op.drop_index(op.f('ix_picker_suggestions_symbol'), table_name='picker_suggestions')
    op.drop_index(op.f('ix_picker_suggestions_suggested_at'), table_name='picker_suggestions')
    op.drop_index(op.f('ix_picker_suggestions_picker_name'), table_name='picker_suggestions')
    op.drop_table('picker_suggestions')
    op.drop_index('ix_discovered_symbols_symbol_picker', table_name='discovered_symbols')
    op.drop_index(op.f('ix_discovered_symbols_symbol'), table_name='discovered_symbols')
    op.drop_index(op.f('ix_discovered_symbols_picker_name'), table_name='discovered_symbols')
    op.drop_index('ix_discovered_symbols_discovered_at', table_name='discovered_symbols')
    op.drop_table('discovered_symbols')
    # ### end Alembic commands ###
