"""Added FK constraint on trades

Revision ID: 4d0cad9906fb
Revises: 554f048e5f99
Create Date: 2026-02-03 14:59:15.290302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0cad9906fb'
down_revision: Union[str, None] = '554f048e5f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'capital_events', 'trades', ['trade_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capital_events', type_='foreignkey')
    # ### end Alembic commands ###
