"""added strategy table

Revision ID: 554f048e5f99
Revises: 1fe0a89ffe50
Create Date: 2026-02-01 20:17:07.663711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554f048e5f99'
down_revision: Union[str, None] = '1fe0a89ffe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capital_events_created_at'), 'capital_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_capital_events_event_type'), 'capital_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_capital_events_trade_id'), 'capital_events', ['trade_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allocation', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sharpe_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('win_rate_30d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=True)
    op.alter_column('system_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_state', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_state', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_capital_events_trade_id'), table_name='capital_events')
    op.drop_index(op.f('ix_capital_events_event_type'), table_name='capital_events')
    op.drop_index(op.f('ix_capital_events_created_at'), table_name='capital_events')
    op.drop_table('capital_events')
    # ### end Alembic commands ###
