"""Changed column from metadata to event metadata

Revision ID: 7f435fea254f
Revises: 86801a1ad798
Create Date: 2026-02-01 15:25:32.598383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f435fea254f'
down_revision: Union[str, None] = '86801a1ad798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('events', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_metadata')
    # ### end Alembic commands ###
